name: Handle Prismic Webhook

on:
  workflow_dispatch: # This allows manual triggering for testing
  repository_dispatch: # This will be used for custom webhook events

jobs:
  handle-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or another version you're using

    - name: Install dependencies
      run: npm install

    - name: Process webhook data
      run: node process-webhook.js
      env:
        WEBHOOK_PAYLOAD: ${{ secrets.WEBHOOK_PAYLOAD }}

  - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Processed video data from webhook"
          git push https://x-access-token:${{ secrets.ACTIONS_PAT2 }}@github.com/mijeonglee806/prismic-test.git HEAD:main